# Generated by Django 5.2.4 on 2026-02-04 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartomante_nome', models.CharField(max_length=100, verbose_name='Nome do Cartomante')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia da Semana')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10, verbose_name='Turno')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_acao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Ação')),
                ('observacao', models.TextField(blank=True, default='', help_text='Motivo da recusa ou observações gerais', verbose_name='Observação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folgas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado Por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_folga', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Folga',
                'verbose_name_plural': 'Solicitações de Folga',
                'db_table': 'solicitacoes_folga',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['status', 'dia_semana'], name='solicitacoe_status_d565c9_idx'), models.Index(fields=['usuario', 'data_solicitacao'], name='solicitacoe_usuario_d752d1_idx'), models.Index(fields=['status'], name='solicitacoe_status_987349_idx')],
            },
        ),
    ]
